---
title: "Another Look at the Monte Hall Problem"
author: "Jeremy Austin"
date: "2025-01-06"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## **Introduction to the Monte Hall Problem**

The Monte Hall problem is a famous problem in probability that stumps many students who hear it for the first time. It is also great teaching opportunity for the necessity of conditional probability. The problem can be stated along the following lines:

1. You (the contestant) are part of a game show and are faced with three boxes, labeled "A","B","C". The host lets you know that two of the boxes are empty, and one contains keys to a new car. They also tell you that there is an equal probability that the keys are contained in any one of the boxes.

2. You must initially select one box, say box A. Upon your selection, the host will open one of the unselected boxes that is empty, say box B.

3. The host gives you the opportunity to switch from your initial selection box A to the remaining un-opened box C.

The problem is to figure out the probabilities that the keys are in each box, given the information from your initial selection and the box that was opened by the host.

## **Important Introductory Probabilty Rules**

- A: Some event
- B: Another event
- $C_i; i=1,...,k$: Series of disjoint events together making up the entire sample space
- ∩: Intersection ("and")
- ∪: Union ("or")
- |: Conditioning on ("given")
- Product rule: $P(A∩B) = P(A|B)P(A) = P(B|A)P(B)$
- Conditional probability rule: $P(A|B) = \frac{P(A∩B)}{P(B)}$
- Total probability rule: $P(A) = P(A∩C_1)+...+P(A∩C_k)$

## **Discussion**

When I was an undergraduate, we talked about this problem in my first calculus-based probability course. Consider a specific scenario, like the initial selection being box A and the exposed box being B. Because the initial distribution is uniform, many students think that after B is eliminated the correct probability distribution looks something along the lines of: 
\
\

| $P(A|\text{Initial A ∩ Exposed B})$ | $P(B|\text{Initial A ∩ Exposed B})$ | $P(C|\text{Initial A ∩ Exposed B})$ |
|:------------------:|:------------------:|:------------------:|
| $\frac{1}{2}$ | $0$ | $\frac{1}{2}$ |
\

Some professors might then pose that the correct solution is different, and give a conditional probability argument to supplement it: 
\
\

$P(A ∩ \text{Initial A ∩ Exposed B}) = P(\text{Exposed B} | A ∩ \text{Initial A})P(\text{Initial A}|A)P(A) = \frac{1}{2}P(\text{Initial A})\frac{1}{3} = P(\text{Initial A})\frac{1}{6}$ \
\

$P(B ∩ \text{Initial A ∩ Exposed B}) = P(\text{Exposed B} | B ∩ \text{Initial A})P(\text{Initial A}|B)P(B) = 0P(\text{Initial A})\frac{1}{3} = 0$ \
\

$P(C ∩ \text{Initial A ∩ Exposed B}) = P(\text{Exposed B} | C ∩ \text{Initial A})P(\text{Initial A}|C)P(C) = 1P(\text{Initial A})\frac{1}{3} = P(\text{Initial A})\frac{1}{3}$ \
\

$P(\text{Initial A ∩ Exposed B}) = P(A ∩ \text{Initial A ∩ Exposed B}) + P(B ∩ \text{Initial A ∩ Exposed B}) + P(C ∩ \text{Initial A ∩ Exposed B})$ \
\

$= P(\text{Initial A})(\frac{1}{6} + 0 + \frac{1}{3}) = P(\text{Initial A})\frac{1}{2}$ \
\

$P(A | \text{Initial A ∩ Exposed B}) = \frac{P(A ∩ \text{Initial A ∩ Exposed B})}{P(\text{Initial A ∩ Exposed B})} = \frac{P(\text{Initial A})\frac{1}{6}}{P(\text{Initial A})\frac{1}{2}} = \frac{1}{3}$ \
\

This solution challenges what a lot of students initially think about the problem because it supports the notion that switching doors increases the probability of getting the keys. It is represented by the following probability distribution:
\
\

| $P(A|\text{Initial A ∩ Exposed B})$ | $P(B|\text{Initial A ∩ Exposed B})$ | $P(C|\text{Initial A ∩ Exposed B})$ |
|:------------------:|:------------------:|:------------------:|
| $\frac{1}{3}$ | $0$ | $\frac{2}{3}$ |
\

When going through this short derivation, I noticed that one important assumption is made: $P(\text{Exposed B} | A ∩ \text{Initial A})$ is chosen to be $\frac{1}{2}$. In other words, it is assumed that in the case of A being initially chosen and the box with the keys, the host has an equal chance of opening either B or C. What if the host employs alternative strategies for the box to reveal? Consider for example a strategy where the host always reveals box B when possible, i.e. when B is not the box with the keys and is not initially chosen. If we re-evaluate the probabilities in our specific scenario:
\
\

$P(B ∩ \text{Initial A ∩ Exposed B}) = P(\text{Exposed B} | A ∩ \text{Initial A})P(\text{Initial A}|A)P(A) = 1P(\text{Initial A})\frac{1}{3}$ \
\

$P(A | \text{Initial A ∩ Exposed B}) = \frac{P(\text{Initial A})\frac{1}{3}}{P(\text{Initial A})\frac{2}{3}} = \frac{1}{2}$ \
\

Which supports the student's original claim for this scenario, and it does not matter whether the contestant switches boxes. Also consider the strategy of always revealing C when possible:
\
\

$P(B ∩ \text{Initial A ∩ Exposed B}) = P(\text{Exposed B} | A ∩ \text{Initial A})P(\text{Initial A}|A)P(A) = P(\text{Initial A})0$ \
\

$P(A | \text{Initial A ∩ Exposed B}) = \frac{P(\text{Initial A})0}{P(\text{Initial A})\frac{1}{3}} = 0$ \
\

Which assigns box C to have the keys with probability 1. Therefore, the contestant should switch. It turns out that regardless of the strategy the host employs, it is always at least as good to switch, therefore the contestant should always switch.

## **FIN**



